# Generated by Django 3.0.1 on 2020-02-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matrimonydata',
            old_name='Dateofbirth',
            new_name='Birthtime',
        ),
    ]
