# Generated by Django 3.0 on 2020-02-03 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matriapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step4',
            old_name='Drinkinghabits',
            new_name='Drinking_habits',
        ),
        migrations.RenameField(
            model_name='step4',
            old_name='Eatinghabits',
            new_name='Eating_habits',
        ),
        migrations.RenameField(
            model_name='step4',
            old_name='Matritalstatus',
            new_name='Marital_status',
        ),
        migrations.RenameField(
            model_name='step4',
            old_name='Smokinghabit',
            new_name='Smoking_habit',
        ),
        migrations.AddField(
            model_name='step1',
            name='EmployedIn',
            field=models.CharField(default=django.utils.timezone.now, max_length=25),
            preserve_default=False,
        ),
    ]
