# Generated by Django 3.0 on 2020-02-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriapp', '0002_auto_20200203_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step4',
            name='prefredheigth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriapp.Heightt'),
        ),
    ]
